import type { ExportPreset } from "@/src/features/export/types";

export const exportPresets: ExportPreset[] = [
  {
    aspectRatio: "9:16",
    captionPositionRecommendation: "Bottom center, above interface chrome",
    captionSafeZone: "Keep captions inside lower 70% with 12% side padding",
    estimatedBitrate: "12-18 Mbps placeholder",
    expectedOrientation: "Vertical Reel",
    id: "tiktok-reels",
    notes: "Best for TikTok, Instagram Reels, and creator-style vertical edits.",
    platform: "TikTok / Reels",
    recommendedCaptionSize: "Large, high-contrast",
    recommendedResolution: "1080 x 1920",
  },
  {
    aspectRatio: "9:16",
    captionPositionRecommendation: "Lower third with generous bottom clearance",
    captionSafeZone: "Avoid bottom 18% for Shorts controls",
    estimatedBitrate: "12-20 Mbps placeholder",
    expectedOrientation: "Vertical Reel",
    id: "youtube-shorts",
    notes: "Optimized for Shorts UI and fast mobile scanning.",
    platform: "YouTube Shorts",
    recommendedCaptionSize: "Large",
    recommendedResolution: "1080 x 1920",
  },
  {
    aspectRatio: "1:1",
    captionPositionRecommendation: "Center-safe lower third",
    captionSafeZone: "Keep all text within 80% square center area",
    estimatedBitrate: "8-12 Mbps placeholder",
    expectedOrientation: "Square",
    id: "square-social",
    notes: "Useful for feeds where square creative still performs well.",
    platform: "Square Social",
    recommendedCaptionSize: "Medium-large",
    recommendedResolution: "1080 x 1080",
  },
  {
    aspectRatio: "4:5",
    captionPositionRecommendation: "Bottom third, restrained styling",
    captionSafeZone: "Keep captions within central 82% width",
    estimatedBitrate: "8-14 Mbps placeholder",
    expectedOrientation: "Vertical Reel",
    id: "linkedin",
    notes: "Professional feed format with cleaner caption treatment.",
    platform: "LinkedIn",
    recommendedCaptionSize: "Medium",
    recommendedResolution: "1080 x 1350",
  },
  {
    aspectRatio: "4:5",
    captionPositionRecommendation: "Bottom third with CTA clearance",
    captionSafeZone: "Avoid edges and leave space for ad UI overlays",
    estimatedBitrate: "10-16 Mbps placeholder",
    expectedOrientation: "Vertical Reel",
    id: "meta-ads",
    notes: "Designed for paid social placements and readable ad captions.",
    platform: "Meta Ads",
    recommendedCaptionSize: "Medium-large",
    recommendedResolution: "1080 x 1350",
  },
  {
    aspectRatio: "16:9",
    captionPositionRecommendation: "Classic lower third",
    captionSafeZone: "Keep captions within lower 25% and 10% side margins",
    estimatedBitrate: "16-24 Mbps placeholder",
    expectedOrientation: "Landscape",
    id: "landscape-youtube",
    notes: "Best for long-form or widescreen YouTube exports.",
    platform: "Landscape YouTube",
    recommendedCaptionSize: "Medium",
    recommendedResolution: "1920 x 1080",
  },
];

export const defaultExportPreset = exportPresets[0];
