import type { CaptionStyle } from "@/src/features/style/types";

export const captionStylePresets: CaptionStyle[] = [
  {
    activeWordHighlight: true,
    activeWordHighlightMode: "color",
    backgroundBox: false,
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 34,
    highlightColor: "#38bdf8",
    id: "momentum-clean",
    name: "Momentum Clean",
    position: "bottom",
    shadowIntensity: 72,
    textColor: "#ffffff",
    textTransform: "none",
  },
  {
    activeWordHighlight: true,
    activeWordHighlightMode: "background-pill",
    backgroundBox: true,
    fontFamily: "Arial Black, Impact, sans-serif",
    fontSize: 38,
    highlightColor: "#facc15",
    id: "bold-opus",
    name: "Bold Opus",
    position: "bottom",
    shadowIntensity: 86,
    textColor: "#ffffff",
    textTransform: "uppercase",
  },
  {
    activeWordHighlight: true,
    activeWordHighlightMode: "scale-pop",
    backgroundBox: true,
    fontFamily: "Trebuchet MS, Arial, sans-serif",
    fontSize: 36,
    highlightColor: "#fb7185",
    id: "creator-pop",
    name: "Creator Pop",
    position: "center",
    shadowIntensity: 64,
    textColor: "#fef3c7",
    textTransform: "uppercase",
  },
  {
    activeWordHighlight: true,
    activeWordHighlightMode: "color",
    backgroundBox: false,
    fontFamily: "SF Pro Display, Inter, Arial, sans-serif",
    fontSize: 30,
    highlightColor: "#a7f3d0",
    id: "minimal-pro",
    name: "Minimal Pro",
    position: "bottom",
    shadowIntensity: 44,
    textColor: "#f8fafc",
    textTransform: "none",
  },
  {
    activeWordHighlight: true,
    activeWordHighlightMode: "scale-pop",
    backgroundBox: false,
    fontFamily: "Impact, Arial Black, sans-serif",
    fontSize: 42,
    highlightColor: "#f97316",
    id: "high-impact",
    name: "High Impact",
    position: "bottom",
    shadowIntensity: 100,
    textColor: "#ffffff",
    textTransform: "uppercase",
  },
];

export const defaultCaptionStyle = captionStylePresets[0];
